# Generated by Django 5.1 on 2024-08-29 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonial_company_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set to true to make this slide the first one displayed.'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the slide in the carousel.'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='content',
            field=models.TextField(blank=True, help_text='Optional description for the slide.'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(help_text='Image for the carousel slide.', upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(help_text='Title of the slide.', max_length=255),
        ),
    ]
