# Generated by Django 5.1 on 2024-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_carousel_options_carousel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Assistant Pastor', 'Assistant Pastor'), ('Elder', 'Elder'), ('Deacon', 'Deacon'), ('Choir Leader', 'Choir Leader'), ('Youth Leader', 'Youth Leader'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Usher', 'Usher'), ('Member', 'Member')], max_length=100),
        ),
    ]
