# Generated by Django 5.1 on 2024-08-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('google', 'Google'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(default='bi', max_length=100)),
            ],
        ),
    ]
