# Generated by Django 5.1 on 2024-08-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('base', 'Base Page'), ('contact', 'Contact Page'), ('mission', 'Mission Page'), ('home', 'Home Page'), ('about-us', 'About Page')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
